version: '3.8'
services:
  postgres_nlw:
    container_name: teste_sifat
    image: postgres
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=sifat_cmv